# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baton < Formula
  desc "Terminal-native TUI for orchestrating multiple Claude Code agents in parallel"
  homepage "https://github.com/devenjarvis/baton"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/baton/releases/download/v0.1.0/baton_0.1.0_darwin_amd64.tar.gz"
      sha256 "0fd32d6b5cc040a53708e00c4d9ebc220aea2023275fc904f2405294e70ea32b"

      define_method(:install) do
        bin.install "baton"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/baton/releases/download/v0.1.0/baton_0.1.0_darwin_arm64.tar.gz"
      sha256 "53081828e88ec0f7dc43ba86e7d738bb552a5447c8aedc263e825525fa76737a"

      define_method(:install) do
        bin.install "baton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/baton/releases/download/v0.1.0/baton_0.1.0_linux_amd64.tar.gz"
      sha256 "47dfc9f44c4222320930a226f727b394c2ed74051a46cb1f0a2904cf887f726b"
      define_method(:install) do
        bin.install "baton"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/baton/releases/download/v0.1.0/baton_0.1.0_linux_arm64.tar.gz"
      sha256 "acad79092f9ce7d464f69b297e8b67cacab4a237c5ea9a2188b92a1957f0110e"
      define_method(:install) do
        bin.install "baton"
      end
    end
  end

  test do
    system "#{bin}/baton", "--help"
  end
end
