# This file was generated by GoReleaser. DO NOT EDIT.
cask "lathe" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "b6c2751dc749575f00b66aa66ab67660b274caa99b569608a4325e70369a4a9b"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ddb0bfb6bafa679b0337e20a58a2281bed7b3f91401a6118ffb20a3c3a81d93"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8701477695b016d75d1df8b3ab41cd2df8285cb6e60451403fb7dc5358bc0047"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9f4f56321e41b2f5f048870f3de1276e4858083434dfb826022e1cd5388e738"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lathe"
  desc "Generate, store, serve, verify, and extend hands-on technical tutorials"
  homepage "https://github.com/devenjarvis/lathe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lathe"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lathe"]
  end

  # No zap stanza required

end
