# This file was generated by GoReleaser. DO NOT EDIT.
cask "lathe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d654e6435ec661aea44e0841b8626731b11cc6e97d47a4fe575b5a12a509e59b"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f55c56b3303e023324e0ea01cfaeaa6ffdc4894715e96c852a92efd93b83505c"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87d8628a5996b0269bb6a243847aa049ad9480d43e9c856b1f35c3e00e83fe24"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3112e49711ce90b405778fcd8c5cd69bf367d30a4695e3b0952e3371466c0887"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lathe"
  desc "Generate, store, serve, verify, and extend hands-on technical tutorials"
  homepage "https://github.com/devenjarvis/lathe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lathe"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lathe"]
  end

  # No zap stanza required

end
