# This file was generated by GoReleaser. DO NOT EDIT.
cask "lathe" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3a07ecc7dabdd1a6809935189b1ba11006b6156f75d4c7b7efb2b808191c06cc"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f77b7ecb2b93eb33cd322e824c5f0453b5295015d88d523b3caeacc6899c9c4"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1234a42f61a88df51c0f13b0968136de4950a57537def23b8fa089ee70b66b4"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "30b77687cd6f74409a552175126bc5568a0eef558ee2427b31eddf23468a78bf"
      url "https://github.com/devenjarvis/lathe/releases/download/v#{version}/lathe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lathe"
  desc "Generate, store, serve, verify, and extend hands-on technical tutorials"
  homepage "https://github.com/devenjarvis/lathe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lathe"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lathe"]
  end

  # No zap stanza required

end
