# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baton < Formula
  desc "Terminal-native TUI for orchestrating multiple Claude Code agents in parallel"
  homepage "https://github.com/devenjarvis/baton"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/baton/releases/download/v0.4.0/baton_0.4.0_darwin_amd64.tar.gz"
      sha256 "5d82d678720eb7fe866f3e66ea3bbd24e7308fdb43f23f53ba0f033adacad49b"

      define_method(:install) do
        bin.install "baton"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/baton/releases/download/v0.4.0/baton_0.4.0_darwin_arm64.tar.gz"
      sha256 "d264bd3f94078a90f0a0b28af2ddaad973b0b72729f4c5743b39047df616d6b1"

      define_method(:install) do
        bin.install "baton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/baton/releases/download/v0.4.0/baton_0.4.0_linux_amd64.tar.gz"
      sha256 "85917fc2d0b5a7bd03fcc083da2cb3b0cabf31afee975a777f63145bd7c22fee"
      define_method(:install) do
        bin.install "baton"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/baton/releases/download/v0.4.0/baton_0.4.0_linux_arm64.tar.gz"
      sha256 "273be239bb44ac0b32e01454225bfa7a2cb1bfcbc2eeb0556023c1d0fcd2a2d0"
      define_method(:install) do
        bin.install "baton"
      end
    end
  end

  test do
    system "#{bin}/baton", "--help"
  end
end
