# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baton < Formula
  desc "Terminal-native TUI for orchestrating multiple Claude Code agents in parallel"
  homepage "https://github.com/devenjarvis/baton"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/baton/releases/download/v0.5.0/baton_0.5.0_darwin_amd64.tar.gz"
      sha256 "28c4cfcfe8fca874eeada49be47f74369725c346a525e83363432d57f224337c"

      define_method(:install) do
        bin.install "baton"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/baton/releases/download/v0.5.0/baton_0.5.0_darwin_arm64.tar.gz"
      sha256 "e00edf71614538eda57e0869b3cab1ab607cb4640c62447f9ee2df622b5a7656"

      define_method(:install) do
        bin.install "baton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/baton/releases/download/v0.5.0/baton_0.5.0_linux_amd64.tar.gz"
      sha256 "e5dfb19ff67e45bd42bfffe59e28eac2f8f3cafb24643f6d4be9d7df600815b1"
      define_method(:install) do
        bin.install "baton"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/baton/releases/download/v0.5.0/baton_0.5.0_linux_arm64.tar.gz"
      sha256 "d7ce9283970a9b2bf28eabf175da207bf97437cc412a001683a432fc736e7ea5"
      define_method(:install) do
        bin.install "baton"
      end
    end
  end

  test do
    system "#{bin}/baton", "--help"
  end
end
