# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moss < Formula
  desc "AI-powered note-taking TUI"
  homepage "https://github.com/devenjarvis/moss"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/moss/releases/download/v0.2.1/moss_0.2.1_darwin_amd64.tar.gz"
      sha256 "826b5a4b70668a73dcb379e45de4d8ccfe1d98716a5bd9dc145664970dba7edc"

      define_method(:install) do
        bin.install "moss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/moss/releases/download/v0.2.1/moss_0.2.1_darwin_arm64.tar.gz"
      sha256 "4c4337cd9114ad930b8b6cb5ca16c11e0f69ad7f8bcc87e28b4364704042052a"

      define_method(:install) do
        bin.install "moss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/moss/releases/download/v0.2.1/moss_0.2.1_linux_amd64.tar.gz"
      sha256 "d57a818ade19b435647548d175ca244182eb3371f786b56da0c574497b9a8282"
      define_method(:install) do
        bin.install "moss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/moss/releases/download/v0.2.1/moss_0.2.1_linux_arm64.tar.gz"
      sha256 "b655751c99f0a7c7fc8fc0964bd8bfc812426e1baf2adfdc4414642d215fd1e0"
      define_method(:install) do
        bin.install "moss"
      end
    end
  end

  test do
    system "#{bin}/moss", "version"
  end
end
