# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moss < Formula
  desc "AI-powered note-taking TUI"
  homepage "https://github.com/devenjarvis/moss"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/moss/releases/download/v0.5.0/moss_0.5.0_darwin_amd64.tar.gz"
      sha256 "2485a8b5cba299137d0d28431d1f2a734aee7311ea201fb5308fe4fb20dda09b"

      define_method(:install) do
        bin.install "moss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/moss/releases/download/v0.5.0/moss_0.5.0_darwin_arm64.tar.gz"
      sha256 "1f6c8b03c9eabb0ed18d3d3dd48925aac28e6d7970b405e0b7adce5ccca3100f"

      define_method(:install) do
        bin.install "moss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/moss/releases/download/v0.5.0/moss_0.5.0_linux_amd64.tar.gz"
      sha256 "bd5076ae16991444c40b4324b2c475e4138d8a903892287ad8b23e9a7302ecda"
      define_method(:install) do
        bin.install "moss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/moss/releases/download/v0.5.0/moss_0.5.0_linux_arm64.tar.gz"
      sha256 "0e5ab349c80dc9365df89aae5bb067d3c2ee2e7dd92e4d5a16f1236c9e561861"
      define_method(:install) do
        bin.install "moss"
      end
    end
  end

  test do
    system "#{bin}/moss", "version"
  end
end
