# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moss < Formula
  desc "AI-powered note-taking TUI"
  homepage "https://github.com/devenjarvis/moss"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/moss/releases/download/v0.1.0/moss_0.1.0_darwin_amd64.tar.gz"
      sha256 "96d4d4e7406703865477bea8baddcbec6f5f0ff181d20075e2ac5e8125cb087f"

      define_method(:install) do
        bin.install "moss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/moss/releases/download/v0.1.0/moss_0.1.0_darwin_arm64.tar.gz"
      sha256 "2173123d9d03a1e794b016f9ed0941d6089a66ed13930f2c1819a9f207d4d9c4"

      define_method(:install) do
        bin.install "moss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/moss/releases/download/v0.1.0/moss_0.1.0_linux_amd64.tar.gz"
      sha256 "1b85e0e5add44b647608933fd70ed2125fa0f3e82473c9d2ddc5097ad0b701da"
      define_method(:install) do
        bin.install "moss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/moss/releases/download/v0.1.0/moss_0.1.0_linux_arm64.tar.gz"
      sha256 "3e3663b37c742f8923260ad04ce7047b69ceea60d65be0968687c93d5a18c113"
      define_method(:install) do
        bin.install "moss"
      end
    end
  end

  test do
    system "#{bin}/moss", "version"
  end
end
