# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Refrain < Formula
  desc "Terminal-native TUI for orchestrating multiple Claude Code agents in parallel"
  homepage "https://github.com/devenjarvis/refrain"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devenjarvis/refrain/releases/download/v0.6.0/refrain_0.6.0_darwin_amd64.tar.gz"
      sha256 "82576474933e29fbc3ca82a3a68fabe0fafb69edbf6dd7e829182ed189d61d8d"

      define_method(:install) do
        bin.install "refrain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devenjarvis/refrain/releases/download/v0.6.0/refrain_0.6.0_darwin_arm64.tar.gz"
      sha256 "db62056fb95e307e51347083cb02ee06d218d620781b8f7bb5137f0ae43ecbc6"

      define_method(:install) do
        bin.install "refrain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/refrain/releases/download/v0.6.0/refrain_0.6.0_linux_amd64.tar.gz"
      sha256 "209da9ca80f2a8ffe2c2b8e7c27a20117b854ae413f846f4cef4241ead64d37e"
      define_method(:install) do
        bin.install "refrain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenjarvis/refrain/releases/download/v0.6.0/refrain_0.6.0_linux_arm64.tar.gz"
      sha256 "f663e882a86bf9ab92ac19fdceeb7e190458944098f72165c0265054f14d1a4b"
      define_method(:install) do
        bin.install "refrain"
      end
    end
  end

  test do
    system "#{bin}/refrain", "--help"
  end
end
